[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
# Use npm install to avoid CI failing when the lockfile isn't in context
cmds = ['npm install --no-audit --no-fund']
dependsOn = ['setup']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']
dependsOn = ['install']

[start]
cmd = 'npm start'

[variables]
NODE_VERSION = '20'
NPM_CONFIG_PRODUCTION = 'false'
NODE_ENV = 'production'
