[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = ['npm ci']
dependsOn = ['setup']

[phases.build]
cmds = ['npm run build']
dependsOn = ['install']

[start]
cmd = 'npm start'

[variables]
NODE_VERSION = '20'
NPM_CONFIG_PRODUCTION = 'false'
NODE_ENV = 'production'
