[phases.setup]
nixPkgs = ['nodejs_20', 'npm']

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'npm start'

[variables]
NODE_VERSION = '20'
NPM_CONFIG_PRODUCTION = 'false'
